version: "2.4"
services:
  api-response-postgres:
    image: postgres:14.9
    container_name: api-response-postgres14.9
    environment:
      - POSTGRES_USER=api-response
      - POSTGRES_PASSWORD=api-response
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    networks:
      - api-response-net
networks:
  api-response-net:
    name: api-response-net